"""empty message

Revision ID: 614ed1ac1b56
Revises: 90fcd83ca880
Create Date: 2023-04-06 01:16:09.983028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614ed1ac1b56'
down_revision = '90fcd83ca880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dept_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dept_name')
    )
    op.add_column('courses', sa.Column('dept_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'departments', ['dept_id'], ['id'])
    op.add_column('instructors', sa.Column('dept_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'instructors', 'departments', ['dept_id'], ['id'])
    op.add_column('students', sa.Column('dept_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'departments', ['dept_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'dept_id')
    op.drop_constraint(None, 'instructors', type_='foreignkey')
    op.drop_column('instructors', 'dept_id')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'dept_id')
    op.drop_table('departments')
    # ### end Alembic commands ###
